<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../diple/modules/xrem/rng_html.xsl"?>
<rng:grammar
  xmlns:rng="http://relaxng.org/ns/structure/1.0"
  xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0"
  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:h="http://www.w3.org/1999/xhtml"
  datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes"
  ns="http://www.tei-c.org/ns/1.0"
  xml:lang="fr"
  >
  <a:documentation>
    <h1 id="cartulaires_v2.rng">
      <a href="http://elec.enc.sorbonne.fr/cartulaires">Les cartulaires numérisés d'Ile-de-France</a>,
      schéma de balisage</h1>
    <ul class="auteurs">
      <li>[PP] Philippe Pons (École nationale des chartes) révision des schémas diplomatiques</li>
    </ul>
    <p>TODO</p>
  </a:documentation>
  
  <!-- TODO innclure les patterns citeStructure et citeData dans le schéma teiHeader -->
  
 <rng:include href="cartulaires.rng">
    
    <rng:define name="encodingDesc">
      <rng:element name="encodingDesc">
        <a:documentation xmlns="http://www.w3.org/1999/xhtml">Documentation technique de l'encodage.</a:documentation>
        <rng:element name="projectDesc">
          <a:documentation xmlns="http://www.w3.org/1999/xhtml">Description scientifique du projet.
            <blockquote>&lt;<a href="http://dublincore.org/documents/dcmi-terms/#terms-description">dc:description</a>&gt;</blockquote>
          </a:documentation>
          <rng:oneOrMore>
            <rng:ref name="teiHeader.p"/>
          </rng:oneOrMore>
        </rng:element>
        <rng:optional>
          <rng:element name="samplingDecl">
            <a:documentation xmlns="http://www.w3.org/1999/xhtml">Etendue numérisée de la source. Préciser par exemple les pages
              qui ne sont pas contenues dans le fichier, et pourquoi.</a:documentation>
            <rng:oneOrMore>
              <rng:ref name="teiHeader.p"/>
            </rng:oneOrMore>
          </rng:element>
        </rng:optional>
        <rng:optional>
          <rng:element name="editorialDecl">
            <a:documentation xmlns="http://www.w3.org/1999/xhtml">Corrections apportées au document source.</a:documentation>
            <rng:oneOrMore>
              <rng:ref name="teiHeader.p"/>
            </rng:oneOrMore>
          </rng:element>
        </rng:optional>
        <!-- issue: comment déclarer le type de document => déclarer que tout le document correspond à une lettre ou à une pièce de théâtre ?-->
        <!-- -->
        <rng:zeroOrMore>
          <rng:element name="refsDecl">
            <rng:oneOrMore>
              <rng:ref name="citeStructure"/>
            </rng:oneOrMore>
          </rng:element>
        </rng:zeroOrMore>
        <!-- -->
      </rng:element>
    </rng:define>
    
    <rng:define name="acte.docDate">
      <rng:element name="docDate">
        <a:documentation>
          <p>La date d'un acte (ou d'une dépêche) est composée idéalement de deux éléments : une date de temps (en nouveau style) et une date de lieu. Ces deux informations sont inégalement disponibles selon les documents et peuvent se trouver sous des formats variés.</p>
          <p>L'éditeur s'efforcera donc de fournir les informations de datation les plus précises disponibles (par examen interne de l'acte ou par recours à des sources externes) dans l'ordre suivant: millésime, quantième et mois et encodera séparément les dates de temps et de lieu.</p>
          <a:example>
            <docDate>
              <placeName>Saint-Germain-en-Laye</placeName>
              <date when="1570-08-31">31 août 1570</date>
            </docDate>
          </a:example>
          <p>D'autres usages, moins normalisés, ont parfois cours dans les éditions anciennes, en particulier au XIX<sup>e</sup> siècle. Le présent schéma propose également des solutions pour encoder les dates telles qu'elles peuvent être présentées dans ces éditions: « Donné le ... à ... ». En cas de reprise d'une édition ancienne, le balisage doit normaliser certaines usages de ponctuation
            <ul>
              <li>Retirer les parenthèses : <del> ( </del> 1er janvier ou 25 mars 1190 - fin 1190 <del> ) </del></li>
              <li>Conserver les crochets (dates reconstituées) : [Vers 1176]</li></ul>
            Le reste de la ponctuation peut être conservée et insérée entre les différents éléments utilisés.
          </p>
          <a:example>
            <docDate>à <placeName>Senlis</placeName>. <date when="0866-01-16">16 janvier 866</date></docDate>
          </a:example>
        </a:documentation>
        <rng:mixed>
          <rng:zeroOrMore>
            <rng:choice>
              <rng:ref name="acte.date"/>
              <rng:ref name="acte.placeName"/>
              <rng:ref name="ref.note"/><!-- PP add ref el -->
            </rng:choice>
          </rng:zeroOrMore>
        </rng:mixed>
      </rng:element>
    </rng:define>
    
    <rng:define name="acte.date">
      <rng:element name="date">
        <a:documentation>Date de temps avec attributs de normalisation (jour, mois, année, intervalles, approximations)
          <blockquote>&lt;<a href="http://dublincore.org/documents/dcmi-terms/#terms-date">dc:date</a>&gt;, 1 ou 2,
            à inférer des combinaisons @when, @notBefore, @notAfter, et @scope.</blockquote>
          
          <p>Une normalisation de la date de temps proposée par le diplomatiste est indispensable : elle permet d'en faciliter l'exploitation lors des requêtes sur le corpus concerné (par exemple pour visualiser la répartition d'un mot selon les siècles ou pour définir des sous-ensembles chronologiques).</p>
          <p>Cette normalisation portera à la fois sur les dates fournies par les actes et sur les dates reconstituées. Toutefois, si elle est aisée lorsque la date est complète, elle peut parfois s'avérer plus délicate pour les dates reconstituées partiellement ou encore en raison de problèmes de conversion des styles anciens de datation.</p>
          <p>
            De fait, l'éditeur peut offrir à son lecteur maintes nuances pour décrire une date de temps. Cette finesse est destinée à la lecture humaine,
            pas à la machine. L'encodage XML doit éviter de perdre de l'information, 
            tout en visant des requêtes efficaces de type base de données.
          </p>
          <p>
            Les dates sont normalisées selon le patron ISO <b>AAAA-MM-JJ</b>, en arrêtant la précision selon ce qui est possible, à l'année, au mois ou au jour près. La mention de l'année est obligatoirement requise&#160;: AAAA(-MM(-JJ)?)?.
          </p>
          <a:example>
            <date when="0950">950</date>
            <date when="1048-04-17">1048, 17 avril</date>
          </a:example>
          <p>Les formats de type <del>--01-01</del> sont donc à proscrire : ils servent normalement à signifier des dates récurrentes (tous les 1<sup>er</sup> janvier). Pour une date dont on ne connait pas l'année mais seulement le jour, il vaut mieux ne rien écrire, car les applications ne pourront pas exploiter utilement l'information. L'utilisation de points d'interrogation, sur le modèle <del>12??</del>, est également à proscrire : non seulement elle ne permet pas de fournir un intervalle précis, mais elle compliquerait les traitements. On encouragera plutôt l'éditeur électronique à déterminer un intervalle chronologique précis et explicite.
          </p>
          <dl class="dl">
            <dt>Problèmes de conversion de style</dt>
            <dd>
              <p>Le soin des éditeurs pour convertir les dates en nouveau style (style du 1<sup>er</sup> janvier) est variable : il n'est donc pas toujours possible de se fier aux dates inscrites par l'éditeur. Aussi on se gardera d'exprimer une date sous le format @when="AAAA-MM-JJ" tant qu'il reste un doute sur le style de datation. Afin d'alerter les applications qu'une décision éditoriale n'a pas été prise, on adoptera un encodage sous forme d'un intervalle (voir ci-dessous).</p>
            </dd>
            <dt>Intervalles</dt>
            <dd>
              <p>Il est fréquent qu'une date de temps soit formulée sous forme d'un intervalle en raison d'un problème de conversion de style ou d'une reconstitution de la date grâce des sources extérieures. Par ailleurs dans le cas d'une date réduite au seul millésime, cet intervalle s'exprimera à partir d'une année-pivot (pas avant ni après cette même année).</p>
              <!-- former examples: <date notBefore="1190-01-01" notAfter="1190-12">1er janvier ou 25 mars 1190 - fin 1190</date>
                <date notBefore="1202-01" notAfter="1202-08">Janvier-août 1202</date>-->
              <a:example>
                <date notBefore="1123-03-26" notAfter="1123-08-03">26 Mars-3 Août 1123</date>
                <date notBefore="1090" notAfter="1096">Entre 1090 et 1096</date>
                <date notBefore="1148-09" notAfter="1150-09">Automne 1148 — Été 1150</date>
                <date notBefore="1138" notAfter="1138">1138</date>
              </a:example>
              <p>Les alternatives entre plusieurs dates (1330 ou 1331, 3 avril ; 1330, 25 mars ou 1331, 3 avril) seront également traitées sous forme d'un intervalle contenant l'ensemble des dates possibles.</p>
              <a:example>
                <date notBefore="1211-01-01" notAfter="1212-03-25">1er janvier ou 3 avril 1211 - 1er janvier ou 25 mars 1212</date>
                <date notBefore="1171-01-25" notAfter="1181-01-25">Frascati, 25 janvier, 1171-1181</date>
              </a:example>
              <p>L'intervalle proposé par l'historien peut également être extrêmement imprécis, faute de renseignements suffisants. Dans ce cas, il faut envisager l'intervalle le plus large possible.</p>
              <a:example>
                <date notBefore="1100" notAfter="1150">Début du xiie siècle</date>
                <date notBefore="1150" notAfter="1200">Fin xiie siècle</date>
                <date notBefore="1100" notAfter="1200">xiie siècle</date>
              </a:example>
            </dd>
            <dt>Dates approximatives (<i>vers</i>, <i>circa</i>)</dt>
            <dd>
              <p>L'historien tient parfois à signaler qu'une date est proche, mais qu'elle
                ne peut être précisée plus. L'attribut @scope est utilisé pour indiquer ce doute. Cet attribut peut être employé pour une date réduite au seul millésime ou non.</p>
              <p>L'étendue de la période définie par cette approximation n'est pas à préciser au moment de l'édition du document : si elle pouvait être déterminée avec certitude, il conviendrait de recourir à un intervalle sous la forme @notAfter, @notBefore. Ce sera plutôt aux moteurs de recherche et aux applications de diffusion de déterminer l'interprétation à faire de cete date approximative, selon le corpus et l'usage que l'on veut en donner (par exemple, considérer que les dates approximatives doivent être traitées comme un intervalle de 5 ans de part et d'autre de la date fournie). </p>
              <!-- former example: <date when="1176" scope="circa">[Vers 1176]</date> -->
              <a:example>
                <date when="1220" scope="circa">Circa 1220</date>
                <date when="1196-09-16" scope="circa">Avant et après le 16 septembre 1196</date>
                <date when="1148-03-25" scope="circa">25 Mars, vers 1148</date>
              </a:example>
            </dd>
            <dt><i>Terminus a quo</i>, <i>terminus ante quem</i></dt>
            <dd>
              <p>Lors de la reconstitution d'une date, il n'est pas toujours possible de définir un intervalle de dates précis : un seul <i>terminus</i> peut être connu.</p>
              <p>Comme pour les dates approximatives, c'est aux moteurs de recherche ou à l'application de diffusion de déterminer automatiquement, selon les besoins, le <i>terminus</i> manquant : même si certaines formules laissent parfois penser que l'écart peut être de moins d'un an, en l'absence de toute recherche complémentaire, on ne saurait fixer un <i>terminus</i> particulier dans ces cas.</p>
              <!-- former examples: <date notAfter="1183">Avant 1183</date>
                <date notBefore="1187">Après 1187</date> -->
              <a:example>
                <date notAfter="1206">Ante a. 1206</date>
                <date notBefore="1181-06">Post. jun. 1181</date>
                <date notBefore="1207-04-22">1207, peu après le 22 avril</date>
                <date notBefore="1122-09-11">Peu après le 11 septembre 1122</date>
              </a:example>
            </dd>
            <dt>Sans date ?</dt>
            <dd>
              <p>L'historien souhaitera évidemment laisser le moins possible de documents non datés.</p>
              <p>Lors de l'encodage d'une édition imprimée, il arrive parfois que la balisage automatique ne retrouve pas une date. C'est très rarement un acte non daté : tantôt on peut par exemple lire <i>Même date</i>, tantôt la date est mentionnée en note. On conseillera d'ajouter cette information de manière invisible (sans modifier le texte encodé), afin qu'elle puisse renseigner l'application, par exemple avec un élément vide comme <a:example><date when="1202"/></a:example>. Lorsque l'acte ne peut réellement être daté, même approximativement, aucune information ne doit être indiquée, même un élément &lt;date> vide. L'interprétation de l'absence est laissée à l'application de publication.</p>
            </dd>
          </dl>
          <!--
            <dt>Difficile à classer</dt>
            <dd>
            <pre>
            &lt;date when="1242-07">date Seconde édition de cette charte, avec la date de juillet 1242 
            (Acte faux. - Copie interpolée, exécutée au XVIIe siècle, sur vélin, 
            et accompagnée d'un sceau équestre dépourvu de légende, 
            qui a été détaché d'un acte ancien à l'aide d'une lame chauffée, 
            puis recollé assez visiblement).&lt;/date>
            
            </pre>
            </dd>
          -->
          
        </a:documentation>
        <rng:optional>
          <rng:choice>
            <rng:group>
              <rng:attribute name="when">
                <rng:ref name="acte.date.type"/>
              </rng:attribute>
            </rng:group>
            <rng:group>
              <rng:attribute name="notBefore">
                <rng:ref name="acte.date.type"/>
              </rng:attribute>
              <rng:attribute name="notAfter">
                <rng:ref name="acte.date.type"/>
              </rng:attribute>
            </rng:group>
            <rng:group>
              <rng:attribute name="notAfter">
                <rng:ref name="acte.date.type"/>
              </rng:attribute>
            </rng:group>
            <rng:group>
              <rng:attribute name="notBefore">
                <rng:ref name="acte.date.type"/>
              </rng:attribute>
            </rng:group>
          </rng:choice>
        </rng:optional>
        <rng:optional>
          <rng:attribute name="scope">
            <rng:choice>
              <rng:value h:title="Vers">circa</rng:value>
            </rng:choice>
          </rng:attribute>
        </rng:optional>
        <rng:zeroOrMore>
          <rng:choice>
            <rng:text/>
            <rng:ref name="abbr"/>
            <rng:ref name="sup"/>
            <rng:ref name="ref.note"/>
            <rng:ref name="note"/><!-- PP add note element (182 cas) -->
            <rng:ref name="sc"/><!-- PP add value "sc" to @rend attribute (8 cas, à garder ?)-->
          </rng:choice>
        </rng:zeroOrMore>
      </rng:element>
    </rng:define>
    
    <rng:define name="teiHeader.title">
      <rng:element name="title">
        <a:documentation xmlns="http://www.w3.org/1999/xhtml">Ligne permettant d'identifier une ressource.
          <blockquote>&lt;<a href="http://dublincore.org/documents/dcmi-terms/#terms-title">dc:title</a>&gt; titre de la notice</blockquote>
        </a:documentation>
        <rng:mixed>
          <rng:zeroOrMore>
            <rng:choice>
              <rng:ref name="lb"/><!-- PP ad lb element (1 seul cas: à supprimer ?) -->
            </rng:choice>
          </rng:zeroOrMore>
        </rng:mixed>
        <text/>
      </rng:element>
    </rng:define>
    
    <rng:define name="sourceDesc">
      <rng:element name="sourceDesc">
        <a:documentation xmlns="http://www.w3.org/1999/xhtml">Description de la source numérisée.
          Le modèle de contenu est pour l'instant limité à la description d'un imprimé (bibl).
          Il pourra être élargi à la description d'un manuscrit (msDesc).
          Cet élément (msDesc) mérite une réflexion attentive dans un schéma distinct.
          <blockquote>&lt;<a href="http://dublincore.org/documents/dcmi-terms/#terms-source">dc:source</a>&gt;, composer une ligne bibliographique avec les éléments contenus.
          </blockquote>
        </a:documentation>
        <rng:choice><!-- PP add optional choice between listBibl or bibl elements (cf. Saint Germain des Près. Peut-être que le cas se posera aussi pour les 2 tomes de Saint-MAgloire et les 4 tomes de Notre Dame. -->
          <rng:element name="listBibl">
            <rng:oneOrMore>
              <rng:ref name="bibl"/>
            </rng:oneOrMore>
          </rng:element>
          <rng:element name="bibl">
            <a:documentation xmlns="http://www.w3.org/1999/xhtml">Référence bibliographique de l'oeuvre numérisée, en texte mêlé ponctuée, avec typographie légère (italique).</a:documentation>
            <rng:optional>
              <rng:element name="abbr">
                <a:documentation xmlns="http://www.w3.org/1999/xhtml">Forme courte de la référence bibliographique, par ex. pour l'inscription répétée de la foliotation.</a:documentation>
                <rng:text/>
              </rng:element>
            </rng:optional>
            <rng:zeroOrMore>
              <rng:choice>
                <rng:text/>
                <rng:ref name="teiHeader.title"/>
                <rng:element name="hi">
                  <rng:attribute name="rend">
                    <rng:choice>
                      <rng:value>i</rng:value>
                      <rng:value>sup</rng:value>
                      <rng:value>sc</rng:value>
                    </rng:choice>
                  </rng:attribute>
                  <rng:text/>
                </rng:element>
                <rng:element name="foreign">
                  <rng:text/>
                </rng:element>
                <rng:element name="publisher">
                  <rng:text/>
                </rng:element>
                <rng:element name="date">
                  <rng:text/>
                </rng:element>
                <rng:element name="author">
                  <rng:text/>
                </rng:element>
              </rng:choice>
            </rng:zeroOrMore>
          </rng:element>
        </rng:choice>
      </rng:element>
    </rng:define>
    
    <rng:define name="pb">
      <rng:element name="pb">
        <a:documentation xmlns="http://www.w3.org/1999/xhtml">Pagination ou foliotation, pour édition électronique d'imprimé ou de manuscrit. Le numéro est obligatoire, sauf dans le cas de pages ou folios manquants, en ce cas une explication est nécessaire.</a:documentation>
        <rng:choice>
          <rng:attribute name="n">
            <a:documentation xmlns="http://www.w3.org/1999/xhtml">Le numéro de page est obligatoire.</a:documentation>
          </rng:attribute>
          <rng:attribute name="ana">
            <a:documentation xmlns="http://www.w3.org/1999/xhtml">Commentaire explicatif s'il n'y a pas de </a:documentation>
          </rng:attribute>
        </rng:choice>
        <rng:optional>
          <rng:choice>
            <rng:attribute name="ed">
              <a:documentation xmlns="http://www.w3.org/1999/xhtml">Référence au témoin dont est issu le numéro de page ou de folio inséré dans l'attribut n.</a:documentation>
            </rng:attribute>
            <rng:attribute name="edRef"/><!-- PP add edRef optional attribute => cf. Saint Germain des Près (conséquence de sourceDesc/listWit -->
          </rng:choice>
        </rng:optional>
        <rng:optional>
          <rng:attribute name="xml:id"/>
        </rng:optional>
        <empty/>
      </rng:element>
    </rng:define>
    
    <rng:define name="witness">
      <rng:element name="witness">
        <a:documentation>Témoin manuscrit d'un acte, dans le tableau de la tradition d'une édition, ou dans un catalogue d'actes. 
          <p>
            La structure générale du contenu reprend l'expérience des références bibliographiques : laisser à l'auteur la souplesse d'agencer à sa convenace la ponctuation, la typographie et les composants, 
            tout en assurant la définition exacte  de certains champs pour extraction vers base de données (dépôt d'archives, cote) ou navigation dans l'édition électronique (identifiant, sigle).
            Le surbalisage est découragé au profit de la fiabilité sur la totalité des corpus.
          </p>
          <p>
            Afin de rester conforme au modèle TEI, tout en restant commode pour le rédacteur, certains éléments autorisés sont interprétés avec souplesse.
            S'il y a « outrage à l'étiquette » (tag abuse), c'est que les étiquettes peuvent mériter des aaménagement pour s'accomoder à la réalité.
            Des remarques précisent les choix les moins naturels.
          </p>
          
          <div><b>Exemple imprimé : </b> <i>Ordonnances des rois de France</i>, 1902—1992.</div>
          <img alt="" src="http://subversion.cru.fr/diple/trunk/schema/witness.png"/>
          
          <p><b>Exemple de présentation</b> : <a href="http://elec.enc.sorbonne.fr/editsdepacification/edit_12#art_12_04">Édit de Nantes</a> (témoins et apparat critique)</p>
          
          <b>Exemples d'encodage</b>
          <a:example>
            <witness><term key="original">Orig.</term> <measure>(54 x 58 cm)</measure> <stamp>jadis sc. sur d. queue</stamp>. <orgName type="repository">Arch. de la Côte-d'Or</orgName>, <num type="idno">C 2971</num>.</witness>
          </a:example>
          <a:example>
            <witness xml:id="edit_14_E"><label>E</label> : Bibl. nat. de France, <num>4° Ld<hi rend="sup">176</hi></num>. 50, p. 1-2 (<num>E<hi rend="sup">1</hi></num>) ;
              <foreign>ibid.</foreign>, <num>4° Ld<hi rend="sup">176</hi></num>. 43, p. 1
              (<num>E<hi rend="sup">2</hi></num>)<desc rend="note" n="1">Dans cette
                édition, l’acte porte le titre suivant : “ Brevet accordé par Henry le Grand
                à ses sujets de la Religion pretendue reformée le 30 (sic) avril 1598
                ”.</desc> ; Anquez, p. 497-498 ; Garrisson, p. 91-93 ; Thomas, p. 73-74.</witness> 
          </a:example>
          <a:example>
            <witness xml:id="edit_01_E"><label>E</label> : <title>Actes royaux</title>, <abbr>n<hi rend="sup">os</hi></abbr> 1667-1670 ; Fontanon, t. 4, p. 267-269 ; Isambert, t. 14, p. 124-129 ; Stegmann, p. 8-14.</witness>
          </a:example>
          <a:example>
            <witness xml:id="smchamps_0896_A"><label>A.</label> Original S 1432, nº <num>4.</num> Sceaux intacts : a) équestre avec bouclier aux armes, très fin : <mentioned rend="sc">† Sigillvm Iohannis de Vernone</mentioned> ; revers à l'écu portant un sautoir alaisé : <mentioned rend="sc">† Clavis secreta</mentioned>. b) d'Élisabeth, en robe flottante à traîne et manteau de même étoffe légère, le bras droit levé approuvant, le gauche replié soutenant un oiseau : <mentioned rend="sc">† Isabellis dne de Nomalia</mentioned> <sic>(sic)</sic>, sans contre-sceau.</witness>
          </a:example>
          
          <b>Compréhension de certains éléments dans le contexte d'un témoin &lt;witness></b>
          
          <dl>
            <dt>&lt;label&gt; ou @n Sigle.</dt>
            <dd>Lettre d'identification pour rappel du témoin dans le corps du texte. Une lettre peut être précisée par des numéros, pouvant paraître en exposant. Le balisage permet de mettre la lettre en gras.  Si @n permet un balisage plus léger et peut être utilisé dans la plupart des cas, &lt;label&gt; devra être utilisé systématiquement pour les sigles complexes (ex: chiffres en exposant).</dd>
            <dt>@xml:id identifiant</dt>
            <dd>Permet d'identifier le témoin pour référence ultérieure, par exemple pour des notes d'apparat critique structurées.</dd>
            <dt>&lt;term key="…"> statut</dt>
            <dd>Terme d'une liste contrôlée pour qualifier le statut de témoin (original, copie, perdu…)</dd>
            <dt>&lt;orgName type="repository"> lieu (institution et pays) de conservation</dt>
            <dd>(2010, TEI n'autorise pas encore  &lt;repository> dans &lt;witness>). Après débats, il a été entendu qu'un dépôt comme les <i>archives impériales</i>, maintenant <i>archives nationales</i> sont moins un lieu qu'une organisation (d'où &lt;orgName>). Ce détail philosophique a ici peu d'importance, pourvu que l'on assure l'attibut avec la valeur fixe <i>repository</i>.</dd>
            <dt>&lt;num type="idno"> cote</dt>
            <dd>La cote d'une pièce d'archive peut traditionnellement présenter des variations typographiques (exposant, petites capitales, parfois indice) ce qui ne permet d'utiliser l'élément &lt;idno>.</dd>
            <dt>&lt;title> titre</dt>
            <dd>Pour l'édition imprimée d'un acte (en italique).</dd>
            <dt>&lt;mentioned> mentions</dt>
            <dd>Texte de mentions dorsales ou hors teneur qui n'est pas reporté dans la transcription (ou dans une note).</dd>
            <dt>&lt;stamp> sceau</dt>
            <dd>Indications sigillographiques.</dd>
            <dt>&lt;emph> italique</dt>
            <dd>Italique sans fonction exploitée (TEI n'autorise pas &lt;hi> dans &lt;witness>)</dd>
            <dt>&lt;abbr>, &lt;num></dt>
            <dd>Suffisent généralement à encadrer les indications en exposant (TEI n'autorise pas &lt;hi> dans &lt;witness>)</dd>
            <dt>&lt;desc type="note"&gt;  note</dt>
            <dd>La TEI n'autorise pas les &lt;note> dans &lt;witness>, de nombreuses éditions imprimées comportent cependant de telles notes.</dd>
          </dl>
          
          
        </a:documentation>
        <rng:ref name="witness.atts"/>
        <rng:zeroOrMore>
          <rng:choice>
            <rng:text/>
            <rng:ref name="label"/>
            <rng:ref name="term"/>
            <rng:ref name="repository"/>
            <rng:ref name="num"/>
            <rng:ref name="title"/>
            <rng:ref name="abbr"/>
            <rng:ref name="rs"/>
            <rng:ref name="persName"/>
            <rng:ref name="placeName"/>
            <rng:ref name="emph"/>
            <rng:ref name="foreign"/>
            <rng:ref name="ref"/>
            <rng:ref name="ref.note"/>
            <rng:ref name="desc"/>
            <rng:ref name="mentioned"/>
            <rng:ref name="sic"/>
            <rng:ref name="q"/>
            <rng:ref name="hi"/><!-- PP add hi element (3000 witness concernés, plus de 6000 cas!) -->
            <rng:ref name="pb"/><!-- PP add pb element (185 witness concernés -->
            <rng:ref name="app"/><!-- PP add app element (2 cas) -->
            <rng:ref name="note"/><!-- PP add note element (84 cas) -->
            <rng:element name="stamp">
              <rng:zeroOrMore>
                <rng:choice>
                  <rng:text/>
                  <rng:ref name="i"/>
                  <rng:ref name="sc"/>
                </rng:choice>
              </rng:zeroOrMore>
            </rng:element>
          </rng:choice>
        </rng:zeroOrMore>
      </rng:element>
    </rng:define>
    
    <rng:define name="transcription">
      <rng:element name="div">
        <a:documentation>Texte de la transcription d'un acte, avec identification de la langue, considéré comme suite paragraphe contenant des phrases.
        </a:documentation>
        <rng:attribute name="type">
          <rng:value>transcription</rng:value>
        </rng:attribute>
        <rng:ref name="lang"/>
        <rng:oneOrMore>
          <rng:choice>
            <rng:ref name="pb"/>
            <rng:ref name="table"/>
            <rng:ref name="note"/>
            <rng:ref name="head"/><!-- PP add head element (plus de 4000 cas dans les cartulaires de Notre Dame et de Saint Germain des Près -->
            <rng:element name="p">
              <rng:optional>
                <rng:ref name="lang"/>
              </rng:optional>
              <rng:mixed>
                <rng:zeroOrMore>
                  <rng:choice>
                    <rng:ref name="pb"/>
                    <rng:ref name="note"/>
                    <rng:ref name="idf.s"/>
                    <rng:ref name="hi"/><!-- PP add hi element (plus de 8000 div)-->
                    <rng:ref name="lb"/><!-- PP ad lb element (100 div) -->
                    <rng:ref name="gap"/><!-- PP add gap element (plus de 100 div) -->
                    <rng:ref name="ref.note"/><!-- PP add ref element => à revoir pour utiliser le système de note sans ref ? -->
                    <rng:ref name="app"/><!-- PP add app element =< pour des notes d'apparat critique. Plus de 300 cas. À conserver ? -->
                  </rng:choice>
                </rng:zeroOrMore>
              </rng:mixed>
            </rng:element>
          </rng:choice>
        </rng:oneOrMore>
      </rng:element>
    </rng:define>
    
    <rng:define name="lb">
      <rng:element name="lb">
        <a:documentation xmlns="http://www.w3.org/1999/xhtml">Saut de ligne, ne pas en abuser, htm:br</a:documentation>
        <rng:optional>
          <rng:attribute name="n"/><!-- PP add n optional attribute (475 cas) -->
        </rng:optional>
        <rng:empty/>
      </rng:element>
    </rng:define>
    
    <rng:define name="acte" combine="choice">
      <rng:element name="text">
        <a:documentation>
          <h2 id="tenor">Structure générale d’un acte</h2>
          <p>Pour un acte francilien de ce corpus, on trouvera une transcription de l'éditeur du XIX<sup>e</sup> ou XX<sup>e</sup> (pas de traduction, ni le texte original, avec les abréviations ou l'absence de ponctuation). Tout acte doit obligatoirement être identifié (@xml:id), numéroté (@n), et paginé (&lt;pb>).</p>
          <dl>
            <dt>@xml:id</dt>
            <dd>L'identifiant aura été inscrit manuellement ou avec un processus supervisé, il est pensé pour être au plus proche de la numérotation du cartulaire, afin que les URIs soient à la fois courtes et signifiantes.</dd>
            <dt>@n</dt>
            <dd>Le numéro d'acte pour affichage. Les pratiques de numérotation des éditions de cartulaires varient beaucoup (chiffres décimaux, romains, avec des bis et des ter…). Certaines éditions n'en comportent pas. L'imprimé ne permet pas toujours de garder une logique parfaitement séquentielle, suite à des insertions ultérieures, ou des suppléments. Cependant ce numéro garde une importance de référence, certains actes sont connus par le numéro d'ordre attribué par l'éditeur. Il est conservé dans un attribut obligatoire, afin d'assurer une désignation courte des items.</dd>
            <dt>&lt;pb></dt>
            <dd>La page où commence l'acte est d'abord conservée pour résoudre les liens depuis les index. Le corpus est destiné à poursuivre une existence purement électronique, le recours à l'image de la page imprimé ne devrait plus être nécessaire. Son utilisation pour la génération d'une référence bibliographique par item est en réflexion.</dd>
          </dl>
        </a:documentation>
        <rng:ref name="split.atts"/>
        <rng:attribute name="xml:id"/>
        <rng:attribute name="n"/>
        <rng:optional>
          <rng:ref name="pb"/><!-- PP pb element is know optional (plus de 5000 actes) -->
        </rng:optional>
        <rng:ref name="acte.front"/>
        <rng:element name="body">
          <rng:zeroOrMore>
            <rng:ref name="note"/>
          </rng:zeroOrMore>
          <rng:choice>
            <rng:ref name="transcription"/>
            <rng:element name="p">
              <rng:empty/>
            </rng:element>
          </rng:choice>
          <rng:zeroOrMore>
            <rng:ref name="note"/>
          </rng:zeroOrMore>
        </rng:element>
        <rng:optional>
          <rng:element name="back">
            <rng:ref name="acte.back"/>
          </rng:element>
        </rng:optional>
      </rng:element>
    </rng:define>
    
    <rng:define name="gap">
      <rng:element name="gap">
        <a:documentation xmlns="http://www.w3.org/1999/xhtml">
          <p>Passage du texte pouvant être ni retranscrit ni restitué, le plus souvent en raison d'un dommage matériel (trou, tâche d'encre, ...). De fait l'élément &lt;gap&gt; est un élément vide auquel des informations complémentaires peuvent être ajoutées en attribut sur la cause de ce trou (@reason)  ou sur sa dimension (@extent).</p>
          <p>&lt;gap&gt; ne doit pas être confondu ni combiné avec &lt;supplied&gt;: le premier est utilisé lorsqu'aucun mot ne peut être restitué, tandis que le second sert à encoder un passage ayant pu être restitué par l'éditeur (à l'aide du contexte ou d'un autre témoin).</p>
          <a:example>Item X s. q ac B. Mazoeirs per los <gap extent="3"/></a:example>
          <a:example>Item <gap reason="cancelled"/></a:example>
        </a:documentation>
        <rng:optional>
          <rng:attribute name="extent"/>
        </rng:optional>
        <rng:optional>
          <rng:attribute name="reason"/><!-- PP each attribute @extent or @reason is optional => NON! Relecture par Olivier pour vérifier s'il s'agit d'un gap[@extent="3"] ou de [...] --> 
        </rng:optional>
        <rng:zeroOrMore>
          <rng:choice>
            <rng:text/>
            <rng:ref name="bornes"/>
          </rng:choice>
        </rng:zeroOrMore>
      </rng:element>
    </rng:define>
    
    <rng:define name="typo.content">
      <a:documentation xmlns="http://www.w3.org/1999/xhtml">Contenu d'une balise typographique</a:documentation>
      <rng:zeroOrMore>
        <rng:choice>
          <rng:text/>
          <rng:ref name="sup"/>
          <rng:ref name="sub"/>
          <rng:ref name="pb"/>
          <!-- balisé automatiquement -->
          <rng:ref name="abbr"/>
          <rng:ref name="note"/>
          <rng:ref name="ref.note"/>
          <rng:ref name="sc"/><!-- PP add value "sc" to rend attribute -->
          <rng:ref name="i"/><!-- PP add value "i" to rend attribute -->
          <rng:ref name="b"/><!-- PP add value "b" to rend attribute -->
        </rng:choice>
      </rng:zeroOrMore>
    </rng:define>
    
    <rng:define name="front">
      <rng:element name="front">
        <a:documentation xmlns="http://www.w3.org/1999/xhtml">Ce modèle de contenu sert d'entête de fichier
          (à ne pas confondre avec le teiHeader qui porte les métadonnées).
          Page de titre, préface, introductions, et autres paratextes d'une édition.</a:documentation>
        <rng:optional>
          <rng:attribute name="xml:id"/><!-- PP add optional attribute @xml:id (pour les fragments) -->
        </rng:optional>
        <rng:choice>
          <rng:ref name="titlePage"/>
          <rng:group>
            <rng:ref name="head"/>
            <rng:zeroOrMore>
              <rng:choice>
                <rng:ref name="docAuthor"/>
                <rng:ref name="docDate"/>
              </rng:choice>
            </rng:zeroOrMore>
            <rng:ref name="argument"/>
            <rng:optional>
              <rng:ref name="byline"/>
            </rng:optional>
          </rng:group>
        </rng:choice>
        <rng:zeroOrMore>
          <rng:ref name="div"/>
        </rng:zeroOrMore>
      </rng:element>
    </rng:define>
    
    <rng:define name="app">
      <rng:element name="app">
        <a:documentation xmlns="http://www.w3.org/1999/xhtml">Entrée d'apparat critique.</a:documentation>
        <rng:optional>
          <rng:attribute name="rend">
            <rng:choice>
              <rng:value h:title="Colonnes pour différentes versions">table</rng:value>
            </rng:choice>
          </rng:attribute>
        </rng:optional>
        <rng:optional>
          <rng:attribute name="n">
            <a:documentation xmlns="http://www.w3.org/1999/xhtml">Numérotation pour appel de note.</a:documentation>
          </rng:attribute>
        </rng:optional>
          <rng:optional>
            <rng:element name="lem">
              <a:documentation xmlns="http://www.w3.org/1999/xhtml">Lemme.</a:documentation>
              <rng:optional>
                <rng:attribute name="wit"/>
              </rng:optional>
              <rng:optional>
                <rng:attribute name="resp"/>
              </rng:optional>
              <rng:zeroOrMore>
                <rng:choice>
                  <rng:text/>
                  <rng:ref name="num"/>
                </rng:choice>
              </rng:zeroOrMore>
            </rng:element>
            <rng:zeroOrMore>
              <rng:element name="rdg">
                <a:documentation xmlns="http://www.w3.org/1999/xhtml">Leçon à l'intérieur d'une variante du texte.</a:documentation>
                <rng:attribute name="wit"/>
                <rng:optional>
                  <rng:attribute name="resp"/>
                </rng:optional>
                <rng:zeroOrMore>
                  <rng:choice>
                    <rng:text/>
                    <rng:ref name="num"/>
                  </rng:choice>
                </rng:zeroOrMore>
              </rng:element>
            </rng:zeroOrMore>
          </rng:optional>
          <rng:zeroOrMore>
            <rng:ref name="hi"/><!-- PP add optional element hi (800 cas dans Saint-Magloire) -->
          </rng:zeroOrMore>
          <rng:optional>
            <rng:ref name="note"/>
          </rng:optional>
      </rng:element>
    </rng:define>

    <rng:define name="head">
      <rng:element name="head">
        <a:documentation xmlns="http://www.w3.org/1999/xhtml">Titre générique.</a:documentation>
        <rng:optional>
          <rng:attribute name="n"/><!-- PP add optional attribute n (269 cas) -->
        </rng:optional>
        <rng:optional>
          <rng:ref name="lang"/>
        </rng:optional>
        <rng:ref name="p.content"/>
      </rng:element>
    </rng:define>
    
    <rng:define name="ref.note">
      <rng:element name="ref">
        <a:documentation xmlns="http://www.w3.org/1999/xhtml">Référence à une note.htm:span class="ref" </a:documentation>
        <rng:optional><!-- PP attribute type is now optional (pour tous les ref dans les index) -->
          <rng:attribute name="type">
            <rng:value>note</rng:value>
          </rng:attribute>
        </rng:optional>
        <rng:optional>
          <rng:attribute name="n">
            <rng:text/>
          </rng:attribute>
        </rng:optional>
        <rng:attribute name="target">
          <rng:text/>
        </rng:attribute>
        <rng:optional>
          <rng:attribute name="xml:id"/>
        </rng:optional>
        <rng:interleave><!-- PP permettre du texte et / ou un élément <hi/> dans un <ref/> pour les renvois dans les index. -->
          <rng:optional>
            <rng:text/>
          </rng:optional>
          <rng:optional>
            <rng:zeroOrMore>
              <rng:ref name="hi"/>
            </rng:zeroOrMore>
          </rng:optional>
        </rng:interleave>
      </rng:element>
    </rng:define>
    
    <rng:define name="list">
      <rng:element name="list">
        <a:documentation xmlns="http://www.w3.org/1999/xhtml">Des listes simples.</a:documentation>
        <rng:attribute name="type">
          <a:documentation xmlns="http://www.w3.org/1999/xhtml">Type de liste, indiqué par un caractère. Le nombre de valeurs est susceptible de s'étendre. 
            En cas d'encodage de texte existant, il peut être plus commode de reporter les numérotations difficiles à générer
            en attribut de l'item (@n).</a:documentation>
          <rng:choice>
            <rng:value h:title="Rien"></rng:value>
            <rng:value h:title="Tiret">-</rng:value>
            <rng:value h:title="Décimale">1</rng:value>
            <rng:value h:title="Chiffres romains">I</rng:value>
            <rng:value h:title="Puce">o</rng:value>
            <rng:value h:title="Index avec navigation alphabétique">index</rng:value>
          </rng:choice>
        </rng:attribute>
        <rng:optional>
          <rng:ref name="head"/>
        </rng:optional>
        <rng:oneOrMore>
          <rng:element name="item">
            <rng:optional>
              <rng:attribute name="xml:id"/>
            </rng:optional>
            <rng:optional>
              <rng:attribute name="n"/>
            </rng:optional>
            <rng:oneOrMore>
              <rng:choice>
                <rng:ref name="p.content"/>
                <rng:ref name="list"/>
                <rng:ref name="p"/><!-- PP add optional element p (seulement 7 cas dans Micy) -->
                <rng:ref name="idf.seg"/><!-- PP add optional element seg (de nombreux cas pour gérer les renvois (ancienne balise custom <rv/> internes dans les index (cf. Saint-Antoine, Saint-Magloire t. 2) -->
              </rng:choice>
            </rng:oneOrMore>
          </rng:element>
        </rng:oneOrMore>
      </rng:element>
    </rng:define>
    
    <rng:define name="table">
      <rng:element name="table">
        <a:documentation xmlns="http://www.w3.org/1999/xhtml">Tables simples (html:table).
          Titre de tableau obligatoire (html:caption).
          Sauts de pages ou colonnes ne coupant pas les lignes.
        </a:documentation>
        <rng:optional>
          <rng:attribute name="rend"/>
        </rng:optional>
        <rng:optional><!-- PP element head is optional (30 tableaux) -->
          <rng:ref name="head"/>
        </rng:optional>
        <rng:oneOrMore>
          <rng:choice>
            <rng:element name="row">
              <rng:optional>
                <rng:attribute name="role">
                  <rng:choice>
                    <rng:value h:title="(défaut) tr/html:td">data</rng:value>
                    <rng:value h:title="tr/html:th">label</rng:value>
                  </rng:choice>
                </rng:attribute>
              </rng:optional>
              <rng:optional>
                <rng:attribute name="rend"/>
              </rng:optional>
              <rng:oneOrMore>
                <rng:element name="cell">
                  <rng:optional>
                    <rng:attribute name="role">
                      <rng:choice>
                        <rng:value h:title="(défaut) html:td">data</rng:value>
                        <rng:value h:title="html:th">label</rng:value>
                      </rng:choice>
                    </rng:attribute>
                  </rng:optional>
                  <rng:optional>
                    <rng:attribute name="rows"/>
                  </rng:optional>
                  <rng:optional>
                    <rng:attribute name="cols"/>
                  </rng:optional>
                  <rng:ref name="p.content"/>
                </rng:element>
              </rng:oneOrMore>
            </rng:element>
            <rng:ref name="pb"/>
            <rng:ref name="cb"/>
          </rng:choice>
        </rng:oneOrMore>
      </rng:element>
    </rng:define>
    
    <rng:define name="idf.seg">
      <rng:element name="seg">
        <a:documentation>Formule ayant pu être reconnue automatiquement.</a:documentation>
        <rng:optional><!-- attribut type optionnel pour les cas où seg remplace la balise custom rv -->
          <rng:attribute name="type">
            <choice>
              <value>theo</value>
            </choice>
          </rng:attribute>
        </rng:optional>
        <rng:zeroOrMore>
          <rng:choice>
            <rng:text/>
            <rng:ref name="ref.note"/>
            <rng:ref name="abbr"/>
            <rng:ref name="typo"/>
            <rng:ref name="pb"/>
            <rng:ref name="persName"/>
          </rng:choice>
        </rng:zeroOrMore>
      </rng:element>
    </rng:define>
    
  </rng:include>
</rng:grammar>