<?xml version="1.0" encoding="UTF-8"?>
<rng:grammar
  xmlns:rng="http://relaxng.org/ns/structure/1.0"
  xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0"
  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:h="http://www.w3.org/1999/xhtml"
  datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes"
  ns="http://www.tei-c.org/ns/1.0"
  xml:lang="fr">
  
  
  
  <rng:define name="refsDecl">
    <rng:element name="refsDecl">
      <a:documentation>
        <p> L'élément <code>refsDecl</code> précise la manière dont les références ont été construites pour ce texte.
          Il fait partie du module "TEI Header" et se place dans <code>encodingDesc</code>.
        </p>
        <p> Dans le projet Cartulaire, il peut contenir des éléments TEI standard comme <code>cRefPattern</code>, <code>refState</code>, ainsi que les extensions éditoriales comme <code>sideStructure</code> </p>
      </a:documentation>
      <rng:zeroOrMore>
        <rng:ref name="citeStructure"/>
      </rng:zeroOrMore>
    </rng:element>
  </rng:define>
  
  <rng:define name="citeStructure">
    <a:documentation>
      <p>L'élement <code>citeStructure</code> déclare la structure et la méthode pour citer le document</p>
      <p>Dans le cadre du projet Cartulaire, cet élément permet que l'API DTS puisse reconstruire automatiquement la structure et les citations</p>
    </a:documentation>
    <rng:element name="citeStructure">
      <rng:attribute name="match"/>
      <rng:attribute name="use"/>
      <rng:optional>
        <rng:attribute name="unit"/>
      </rng:optional>
      <rng:optional>
        <rng:attribute name="delim"/>
      </rng:optional>
      <rng:zeroOrMore>
        <rng:ref name="citeData"/>
      </rng:zeroOrMore>
      <rng:zeroOrMore>
        <rng:ref name="citeStructure"/>
      </rng:zeroOrMore>
    </rng:element>
  </rng:define>
  
  <rng:define name="citeData">
    <a:documentation>
      <p>L'élement <code>citeData</code> permet,uniquement dans citeStructure, d'attacher des métadonnées calculées pour chacune des unités de citation.</p>
      <p>Dans le projet des Cartulaires, citeData permet de faire une entrée de catalogue qui est utilisée dans l'API DTS, l'interface de navigation, les métadonnées DublinCore ainsi que les collections. Sans citedata, DTS ne reconnaît rien du titre d'un acte, de sa date, de son type diplomatique ni de la langue de sa transcription.</p>
    </a:documentation>
    <rng:element name="citeData">
      <rng:attribute name="property"/>
      <rng:attribute name="use"/>
    </rng:element>
  </rng:define>
  
  
  <!-- insérer documentation sur <choice> dès que cela aura été validé. De même choice pourra être utilisé pour combiner add et del. -->
  
  <rng:start combine="choice">
    <a:documentation xmlns="http://www.w3.org/1999/xhtml">Nécessaire à la validation du schéma</a:documentation>
    <rng:ref name="refsDecl"/>
  </rng:start>  
  
</rng:grammar>
